name: mmoc_teach
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.0.0
  file_picker: ^10.3.3

  # Open YouTube Videos
  url_launcher: ^6.3.1
  youtube_player_iframe: ^5.2.0
  shared_preferences: ^2.5.3

  # Certificate Packages
  pdf: ^3.11.0
  printing: ^5.13.4
  google_sign_in: ^7.2.0
  syncfusion_flutter_pdfviewer: ^33.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/app_logo.png
    - assets/logo/
    - assets/animations/
    - assets/notes/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"