// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACUJzP7ewo8t4C_eygIJi1FkuYoIMgHA',
    appId: '1:389424571531:web:aaf097ebfc77dfa789a08e',
    messagingSenderId: '389424571531',
    projectId: 'mmoc-teach',
    authDomain: 'mmoc-teach.firebaseapp.com',
    storageBucket: 'mmoc-teach.firebasestorage.app',
    measurementId: 'G-B4GNQE12N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwXKThStGqHdAAgsTgp-1mKnmorVUlBX4',
    appId: '1:389424571531:android:250a52dee5227d5089a08e',
    messagingSenderId: '389424571531',
    projectId: 'mmoc-teach',
    storageBucket: 'mmoc-teach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmAZrAxTyTdwOl0A6VXYJG578SrBm9rqE',
    appId: '1:389424571531:ios:150ff50fc4a3bcd189a08e',
    messagingSenderId: '389424571531',
    projectId: 'mmoc-teach',
    storageBucket: 'mmoc-teach.firebasestorage.app',
    iosBundleId: 'com.example.mmocTeach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmAZrAxTyTdwOl0A6VXYJG578SrBm9rqE',
    appId: '1:389424571531:ios:150ff50fc4a3bcd189a08e',
    messagingSenderId: '389424571531',
    projectId: 'mmoc-teach',
    storageBucket: 'mmoc-teach.firebasestorage.app',
    iosBundleId: 'com.example.mmocTeach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACUJzP7ewo8t4C_eygIJi1FkuYoIMgHA',
    appId: '1:389424571531:web:72f35019e1755c5489a08e',
    messagingSenderId: '389424571531',
    projectId: 'mmoc-teach',
    authDomain: 'mmoc-teach.firebaseapp.com',
    storageBucket: 'mmoc-teach.firebasestorage.app',
    measurementId: 'G-H4Z8ZM4SYZ',
  );
}
